name: CI/CD

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    env:
      AWS_REGION: us-east-1
      ACCOUNT_ID: ${{ secrets.AWS_ACCOUNT_ID }}

    steps:
      - name: Checkout repo
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.13'

      - name: Create virtual environment & install dependencies
        run: |
          python -m venv .venv
          .venv/bin/python -m pip install --upgrade pip
          .venv/bin/pip install -r requirements.txt
          .venv/bin/pip install pytest

      - name: Run unit tests
        run: |
          .venv/bin/pytest -v tests/

      - name: Install AWS CDK CLI
        run: |
          npm install -g aws-cdk

      - name: CDK synth
        run: |
          .venv/bin/python -m pip install -r requirements.txt
          cdk synth

      - name: CDK diff
        run: |
          cdk diff

      # Optional: Deploy to sandbox
      # Uncomment below if you want automatic deployment
      # - name: CDK deploy
      #   run: |
      #     cdk deploy --require-approval never
