name: CDK Deploy

on:
  push:
    branches:
      - main

jobs:
  cdk:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout code
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python 3.13
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # 3. Create & activate virtual environment
      - name: Setup virtual environment
        run: |
          python -m venv .venv
          source .venv/bin/activate
          python -m pip install --upgrade pip

      # 4. Install Python dependencies
      - name: Install requirements
        run: |
          source .venv/bin/activate
          pip install -r requirements.txt

      # 5. Install CDK CLI globally
      - name: Install CDK CLI
        run: npm install -g aws-cdk

      # 6. Run tests
      - name: Run pytest
        run: |
          source .venv/bin/activate
          pip install pytest
          pytest -v tests/

      # 7. Bootstrap CDK (if needed)
      - name: CDK bootstrap
        run: |
          source .venv/bin/activate
          cdk bootstrap

      # 8. Synthesize CDK
      - name: CDK synth
        run: |
          source .venv/bin/activate
          cdk synth

      # 9. Deploy CDK
      - name: CDK deploy
        run: |
          source .venv/bin/activate
          cdk deploy --require-approval never
