name: CDK CI/CD

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  cdk:
    runs-on: ubuntu-latest

    steps:
      # 1. Checkout repo
      - name: Checkout repository
        uses: actions/checkout@v3

      # 2. Setup Python
      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.13

      # 3. Install Python dependencies
      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      # 4. Run unit tests
      - name: Run unit tests
        run: |
          python -m venv .venv
          source .venv/bin/activate
          pytest -v tests/

      # 5. Install CDK
      - name: Install AWS CDK
        run: npm install -g aws-cdk

      # 6. Bootstrap CDK environment (optional)
      #- name: CDK Bootstrap
      #  run: cdk bootstrap aws://$AWS_ACCOUNT_ID/$AWS_REGION

      # 7. CDK synth
      - name: CDK Synth
        run: cdk synth

      # 8. CDK diff
      - name: CDK Diff
        run: cdk diff
