name: CI/CD Pipeline

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # 1. Checkout code
    - name: Checkout repository
      uses: actions/checkout@v3

    # 2. Set up Python
    - name: Set up Python 3.13
      uses: actions/setup-python@v4
      with:
        python-version: 3.13

    # 3. Install dependencies in a virtual environment
    - name: Install dependencies
      run: |
        python -m venv .venv
        source .venv/bin/activate
        python -m pip install --upgrade pip
        pip install -r requirements.txt

    # 4. Run unit tests
    - name: Run tests
      run: |
        source .venv/bin/activate
        pytest -v tests/

    # 5. CDK synth (generate CloudFormation template)
    - name: CDK synth
      run: |
        source .venv/bin/activate
        npx cdk synth

    # 6. CDK diff (compare local stack with deployed stack)
    - name: CDK diff
      run: |
        source .venv/bin/activate
        npx cdk diff
